// Banco de preguntas de Nivel Bajo (Álgebra Básica y Reducción)
const bancoBajo = [
    { pregunta: "¿Cuál es el resultado de reducir los términos semejantes: $3x + 5x - 2x$?", correcta: "$6x$", distractoras: ["$10x$", "$6x^2$", "$4x$"] },
    { pregunta: "Si $x = 3$, ¿cuál es el valor numérico de $2x + 4$?", correcta: "$10$", distractoras: ["$9$", "$14$", "$6$"] },
    { pregunta: "¿Cuál es el coeficiente numérico del término $-7x^2y$?", correcta: "$-7$", distractoras: ["$7$", "$2$", "$-2$"] },
    { pregunta: "¿Qué nombre recibe una expresión algebraica que consta de un solo término?", correcta: "Monomio", distractoras: ["Binomio", "Trinomio", "Polinomio"] },
    { pregunta: "Al multiplicar $x^3 \\cdot x^2$, ¿cuál es el resultado?", correcta: "$x^5$", distractoras: ["$x^6$", "$2x^5$", "$x$"] },
    { pregunta: "¿Cuál es el resultado de la suma: $(2a + 3b) + (5a - b)$?", correcta: "$7a + 2b$", distractoras: ["$10a - 3b$", "$7a + 4b$", "$8ab$"] },
    { pregunta: "¿Cuál es el grado absoluto del monomio $4x^3y^2$?", correcta: "$5$", distractoras: ["$3$", "$2$", "$6$"] },
    { pregunta: "¿Cuál es el valor numérico de $a^2$ cuando $a = -4$?", correcta: "$16$", distractoras: ["$-16$", "$-8$", "$8$"] },
    { pregunta: "Al dividir $x^8 / x^2$, ¿cuál es el resultado?", correcta: "$x^6$", distractoras: ["$x^4$", "$x^{10}$", "$x^{16}$"] },
    { pregunta: "¿Qué expresión representa 'el triple de un número aumentado en 5'?", correcta: "$3x + 5$", distractoras: ["$x^3 + 5$", "$3(x + 5)$", "$5x + 3$"] },
    { pregunta: "Simplifica la expresión: $4m - 9m$", correcta: "$-5m$", distractoras: ["$5m$", "$-13m$", "$13m$"] },
    { pregunta: "¿Cuál es el resultado de $(a^2)(a^3)(a)$?", correcta: "$a^6$", distractoras: ["$a^5$", "$a^9$", "$3a^6$"] },
    { pregunta: "Dos términos son semejantes cuando tienen:", correcta: "La misma parte literal y mismos exponentes", distractoras: ["El mismo coeficiente", "El mismo signo", "Los mismos números"] },
    { pregunta: "¿Cuál es el resultado de evaluar $5 - x$ cuando $x = -2$?", correcta: "$7$", distractoras: ["$3$", "$-7$", "$-3$"] },
    { pregunta: "Si restamos $(3x)$ de $(8x)$, obtenemos:", correcta: "$5x$", distractoras: ["$-5x$", "$11x$", "$-11x$"] },
    { pregunta: "¿Cuál es el resultado de $0 \\cdot (4x^2 - 2x + 1)$?", correcta: "$0$", distractoras: ["$4x^2 - 2x + 1$", "$1$", "$x$"] },
    { pregunta: "¿Cómo se llama una expresión algebraica de tres términos?", correcta: "Trinomio", distractoras: ["Monomio", "Binomio", "Cuatrinomio"] },
    { pregunta: "Al elevar $(2x)^3$, ¿cuál es el resultado?", correcta: "$8x^3$", distractoras: ["$6x^3$", "$2x^3$", "$8x$"] },
    { pregunta: "Identifica la parte literal en el término $-12ab^2$:", correcta: "$ab^2$", distractoras: ["$-12$", "$12$", "$a^2b$"] },
    { pregunta: "Reduce la expresión: $y + y + y$", correcta: "$3y$", distractoras: ["$y^3$", "$3 + y$", "$y/3$"] },
    { pregunta: "¿Cuál es el resultado de $10x - (3x + 2x)$?", correcta: "$5x$", distractoras: ["$9x$", "$15x$", "$5$"] },
    { pregunta: "Si $y = -1$, calcula el valor de $3y + 7$:", correcta: "$4$", distractoras: ["$-10$", "$10$", "$-4$"] },
    { pregunta: "¿Cuál es el perímetro de un cuadrado de lado $2x$?", correcta: "$8x$", distractoras: ["$4x^2$", "$4x$", "$2x^4$"] },
    { pregunta: "Al multiplicar $(-3a)(2b)$, se obtiene:", correcta: "$-6ab$", distractoras: ["$6ab$", "$-5ab$", "$-6a^2b^2$"] },
    { pregunta: "Simplifica la expresión: $\\frac{12x^4}{4x}$", correcta: "$3x^3$", distractoras: ["$3x^4$", "$8x^3$", "$3x$"] },
    { pregunta: "¿Cuál es el valor numérico de $x^0$ para cualquier $x \\neq 0$?", correcta: "$1$", distractoras: ["$0$", "$x$", "Indefinido"] },
    { pregunta: "En la expresión $-x$, ¿cuál es el coeficiente numérico implícito?", correcta: "$-1$", distractoras: ["$0$", "$1$", "$-x$"] },
    { pregunta: "¿Cuál es el resultado de $5a - 5a$?", correcta: "$0$", distractoras: ["$a$", "$10a$", "$1$"] },
    { pregunta: "Expresa en lenguaje algebraico: 'La mitad de un número $x$':", correcta: "$\\frac{x}{2}$", distractoras: ["$2x$", "$x - 2$", "$x^2$"] },
    { pregunta: "Al realizar $(x + 2) + (x - 2)$, se obtiene:", correcta: "$2x$", distractoras: ["$0$", "$2x + 4$", "$x^2 - 4$"] }
];