// Banco de preguntas de Nivel Intermedio (Función Exponencial)
const bancoIntermedio = [
    { pregunta: "Si $f(x) = 2^x$, ¿cuál es el valor de $f(4)$?", correcta: "16", distractoras: ["8", "32", "64"] },
    { pregunta: "En la función exponencial $g(x) = 3^x$, el punto de corte con el eje Y es:", correcta: "$(0, 1)$", distractoras: ["$(0, 3)$", "$(1, 0)$", "$(0, 0)$"] },
    { pregunta: "Al simplificar la expresión exponencial $e^x \\cdot e^3$, obtenemos:", correcta: "$e^{x + 3}$", distractoras: ["$e^{3x}$", "$e^{x - 3}$", "$3e^x$"] },
    { pregunta: "Dada la función $f(x) = (0.5)^x$, ¿cuál es su comportamiento gráfico?", correcta: "Es estrictamente decreciente", distractoras: ["Es estrictamente creciente", "Es una recta horizontal", "Corta al eje X"] },
    { pregunta: "¿Cuál es la solución de la ecuación exponencial $2^x = 32$?", correcta: "$x = 5$", distractoras: ["$x = 4$", "$x = 16$", "$x = 6$"] },
    { pregunta: "Al evaluar $f(x) = 5^x$ en $x = -2$, se obtiene:", correcta: "$\\frac{1}{25}$", distractoras: ["$-25$", "$-10$", "$25$"] },
    { pregunta: "Simplifica la potencia de una potencia $(3^x)^2$:", correcta: "$3^{2x}$", distractoras: ["$3^{x + 2}$", "$9^{2x}$", "$3^{x^2}$"] },
    { pregunta: "¿Cuál es la asíntota horizontal de la función $f(x) = 4^x$?", correcta: "$y = 0$", distractoras: ["$x = 0$", "$y = 1$", "$y = 4$"] },
    { pregunta: "Resuelve la ecuación exponencial $3^{2x - 1} = 27$:", correcta: "$x = 2$", distractoras: ["$x = 1$", "$x = 3$", "$x = 4$"] },
    { pregunta: "En el modelo de crecimiento $P(t) = 100 \\cdot 2^t$, ¿cuál es la población inicial ($t = 0$)?", correcta: "$100$", distractoras: ["$200$", "$0$", "$1002$"] },
    { pregunta: "¿Cuál es el resultado de dividir $5^x / 5^2$?", correcta: "$5^{x - 2}$", distractoras: ["$5^{x / 2}$", "$1^{x - 2}$", "$5^{2 - x}$"] },
    { pregunta: "Si la base $a$ de una función $f(x) = a^x$ cumple que $a > 1$, la función es:", correcta: "Creciente", distractoras: ["Decreciente", "Constante", "Negativa"] },
    { pregunta: "Al expresar $\\sqrt{2^x}$ en forma de exponente fraccionario se obtiene:", correcta: "$2^{x/2}$", distractoras: ["$2^{2x}$", "$2^{x - 2}$", "$4^x$"] },
    { pregunta: "En la función $f(x) = 2 \\cdot 3^x$, ¿cuál es el corte con el eje Y?", correcta: "$(0, 2)$", distractoras: ["$(0, 3)$", "$(0, 6)$", "$(0, 1)$"] },
    { pregunta: "Resuelve para $x$: $4^x = \\frac{1}{16}$", correcta: "$x = -2$", distractoras: ["$x = 2$", "$x = -4$", "$x = 1/4$"] },
    { pregunta: "Al aplicar la propiedad del producto $(2^x)(4^x)$, expresado en base 2 equivale a:", correcta: "$2^{3x}$", distractoras: ["$8^{2x}$", "$2^{2x}$", "$6^x$"] },
    { pregunta: "Si $f(x) = 10^x$, ¿cuál es el valor de $f(-1)$?", correcta: "$0.1$", distractoras: ["$-10$", "$-0.1$", "$1$"] },
    { pregunta: "¿Por qué la base $a$ de una función exponencial real debe ser positiva ($a > 0$)?", correcta: "Para evitar resultados no reales en exponentes fraccionarios", distractoras: ["Porque la función se cancela", "Porque da cero", "Porque no existen negativos"] },
    { pregunta: "Resuelve la ecuación $e^{x+1} = e^5$:", correcta: "$x = 4$", distractoras: ["$x = 5$", "$x = 6$", "$x = 1$"] },
    { pregunta: "Una sustancia se desintegra según $N(t) = N_0 \\cdot (\\frac{1}{2})^t$. Tras $t = 3$, ¿qué fracción queda?", correcta: "$\\frac{1}{8}$", distractoras: ["$\\frac{1}{6}$", "$\\frac{1}{4}$", "$\\frac{1}{2}$"] },
    { pregunta: "¿Cuál es el dominio de la función $f(x) = 3^x$?", correcta: "Todos los números reales $(-\\infty, \\infty)$", distractoras: ["Solo reales positivos $(0, \\infty)$", "Reales excepto $0$", "Enteros positivos"] },
    { pregunta: "¿Cuál es el rango de la función $f(x) = 2^x$?", correcta: "$(0, \\infty)$", distractoras: ["$[-\\infty, \\infty]$", "$[1, \\infty)$", "$(-\\infty, 0)$"] },
    { pregunta: "Si $2^{x+3} = 2^7$, entonces $x$ es igual a:", correcta: "$4$", distractoras: ["$7$", "$3$", "$10$"] },
    { pregunta: "Calcula $f(3)$ si $f(x) = 4 \\cdot 2^{-x}$:", correcta: "$\\frac{1}{2}$", distractoras: ["$2$", "$-2$", "$\\frac{1}{4}$"] },
    { pregunta: "¿Qué le ocurre a la gráfica de $f(x) = 2^x + 3$ respecto a $2^x$?", correcta: "Se desplaza 3 unidades hacia arriba", distractoras: ["Se desplaza 3 a la derecha", "Se estira verticalmente", "Se desplaza 3 hacia abajo"] },
    { pregunta: "La solución de $9^x = 27$ es:", correcta: "$x = 1.5$", distractoras: ["$x = 3$", "$x = 2$", "$x = 0.5$"] },
    { pregunta: "¿Cuál expresión equivale a $(e^x)^0$?", correcta: "$1$", distractoras: ["$e^x$", "$0$", "$e$"] },
    { pregunta: "Evalúa $(1/3)^{-2}$:", correcta: "$9$", distractoras: ["$-9$", "$\\frac{1}{9}$", "$-6$"] },
    { pregunta: "Si $5^x = 1$, el valor de $x$ es:", correcta: "$0$", distractoras: ["$1$", "$5$", "$-1$"] },
    { pregunta: "Simplifica $\\frac{2^{x+2}}{2^x}$:", correcta: "$4$", distractoras: ["$2$", "$2^2x$", "$1$"] }
];